=== justeattakeaway/httpclient-interception/src/HttpClientInterception/Bundles/http-request-bundle-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$id": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "title": "JSON Schema for HTTP request interception bundles for use with JustEat.HttpClientInterception.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "The bundle's optional ID."
    },
    "comment": {
      "type": "string",
      "description": "An optional comment describing the bundle."
    },
    "version": {
      "type": "number",
      "description": "The bundle version.",
      "default": 1,
      "minimum": 1
    },
    "items": {
      "type": "array",
      "description": "An array of HTTP request interceptions.",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The item's optional ID."
          },
          "comment": {
            "type": "string",
            "description": "An optional comment describing the item."
          },
          "version": {
            "type": "string",
            "description": "The optional HTTP version for the request."
          },
          "method": {
            "type": "string",
            "description": "The optional HTTP version for the request.",
            "default": "GET"
          },
          "uri": {
            "type": "string",
            "description": "The absolute URI for the HTTP request."
          },
          "ignorePath": {
            "type": "boolean",
            "description": "Whether to ignore the URI's path when matching the interception.",
            "default": false
          },
          "ignoreQuery": {
            "type": "boolean",
            "description": "Whether to ignore the URI's query string when matching the interception.",
            "default": false
          },
          "priority": {
            "type": "integer",
            "description": "The optional priority value for the item."
          },
          "status": {
            "type": "string",
            "description": "The optional HTTP status code for the request. This can be either an integer or an HttpStatusCode enum value.",
            "default": "200"
          },
          "requestHeaders": {
            "type": "object",
            "description": "The optional HTTP request headers to specify for the interception to match.",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "responseHeaders": {
            "type": "object",
            "description": "The optional HTTP response headers to return for the interception.",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "contentHeaders": {
            "type": "object",
            "description": "The optional response content headers for the interception.",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "contentFormat": {
            "type": "string",
            "enum": [ "base64", "json", "string" ],
            "description": "The format of the response's content body.",
            "default": "string"
          },
          "contentJson": {
            "description": "The response's content body expressed as JSON.",
            "oneOf": [
              {
                "type": "object"
              },
              {
                "type": "array"
              }
            ]
          },
          "contentString": {
            "type": "string",
            "description": "The response's content expressed as a string or Base64 encoded string.",
            "default": ""
          },
          "templateValues": {
            "type": "object",
            "description": "The optional template key-value pairs to apply to the URI, headers or content.",
            "additionalProperties": {
              "type": "string"
            }
          },
          "skip": {
            "type": "boolean",
            "description": "Whether to skip the item so it is not used.",
            "default": false
          }
        },
        "required": [ "uri" ]
      },
      "additionalItems": false,
      "uniqueItems": true
    }
  },
  "required": [ "items" ]
}

=== justeattakeaway/httpclient-interception/tests/HttpClientInterception.Tests/Bundles/templated-bundle-base64.json
{
  "$schema": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "id": "templated-base64-string-bundle",
  "comment": "An HTTP request bundle that uses templating for a Base64-encoded string.",
  "version": 1,
  "items": [
    {
      "comment": "An HTTP request for a Base64-encoded string that uses templating.",
      "uri": "https://www.just-eat.co.uk/",
      "contentFormat": "base64",
      "contentString": "PGh0bWw+PGhlYWQ+PHRpdGxlPiR7Q29tcGFueU5hbWV9PC90aXRsZT48L2hlYWQ+PC9odG1sPg==",
      "templateValues": {
        "CompanyName": "Just Eat"
      }
    }
  ]
}

=== justeattakeaway/httpclient-interception/tests/HttpClientInterception.Tests/Bundles/skipped-item-bundle.json
{
  "$schema": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "id": "test-skipped-item-bundle-bundle",
  "comment": "An HTTP request bundle where the item is skipped.",
  "version": 1,
  "items": [
    {
      "id": "html",
      "comment": "A skipped HTTP request.",
      "uri": "https://www.just-eat.co.uk/",
      "contentHeaders": {
        "content-type": [
          "text/html; charset=utf-8"
        ]
      },
      "contentString": "<html><head><title>Just Eat</title></head></html>",
      "skip": true
    }
  ]
}

=== justeattakeaway/httpclient-interception/tests/HttpClientInterception.Tests/Bundles/content-as-html-string.json
{
  "$schema": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "id": "content-as-html-string-bundle",
  "comment": "An HTTP request bundle with content as a string.",
  "version": 1,
  "items": [
    {
      "id": "html",
      "comment": "An HTTP request that returns an HTML string.",
      "uri": "https://www.just-eat.co.uk/",
      "contentString": "<html><head><title>Just Eat</title></head></html>"
    }
  ]
}

=== justeattakeaway/httpclient-interception/tests/HttpClientInterception.Tests/Bundles/templated-bundle-json.json
{
  "$schema": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "id": "templated-json-bundle",
  "comment": "An HTTP request bundle that uses templating for JSON.",
  "version": 1,
  "items": [
    {
      "comment": "An HTTP request for a JSON response that uses templating.",
      "uri": "https://api.github.com/orgs/${CompanyName}",
      "contentFormat": "json",
      "contentJson": {
        "id": 1516790,
        "login": "justeattakeaway",
        "url": "https://api.github.com/orgs/${CompanyName}",
        "avatar_url": "${AvatarUrl}",
        "name": "${Name}",
        "blog": "${BlogUrl}"
      },
      "templateValues": {
        "CompanyName": "justeattakeaway",
        "Name": "JustEatTakeaway"
      }
    },
    {
      "comment": "An HTTP request for a JSON response that uses templating.",
      "uri": "https://api.github.com/orgs/${CompanyName}/repos",
      "contentFormat": "json",
      "contentJson": [
        {
          "id": 123456,
          "name": "${RepoName}",
          "full_name": "${CompanyName}/${RepoName}",
          "private": false,
          "owner": {
            "login": "${CompanyName}",
            "id": 1516790
          }
        }
      ],
      "templateValues": {
        "CompanyName": "justeattakeaway",
        "RepoName": "httpclient-interception"
      }
    }
  ]
}

=== justeattakeaway/httpclient-interception/tests/HttpClientInterception.Tests/Bundles/content-as-html-base64.json
{
  "$schema": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "id": "content-as-base64-string-bundle",
  "comment": "An HTTP request bundle with content as a Base64 string.",
  "version": 1,
  "items": [
    {
      "id": "html",
      "comment": "An HTTP request that returns a Base64-encoded HTML string.",
      "uri": "https://www.just-eat.co.uk/",
      "contentFormat": "base64",
      "contentString": "PGh0bWw+PGhlYWQ+PHRpdGxlPkp1c3QgRWF0PC90aXRsZT48L2hlYWQ+PC9odG1sPg=="
    }
  ]
}

=== justeattakeaway/httpclient-interception/tests/HttpClientInterception.Tests/Bundles/header-matching.json
{
  "$schema": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "id": "test-http-request-bundle",
  "comment": "An HTTP request bundle for testing HTTP request header matching for the same URL.",
  "version": 1,
  "items": [
    {
      "id": "authorized",
      "comment": "An HTTP request with an Authorization header.",
      "uri": "https://registry.hub.docker.com/v2/user/image/manifests/latest",
      "requestHeaders": {
        "Accept": [
          "application/vnd.oci.image.index.v1+json"
        ],
        "Authorization": [
          "Bearer not-a-real-docker-hub-token"
        ]
      },
      "contentString": "authorized"
    },
    {
      "id": "unauthorized",
      "comment": "An HTTP request without an Authorization header.",
      "uri": "https://registry.hub.docker.com/v2/user/image/manifests/latest",
      "requestHeaders": {
        "Accept": [
          "application/vnd.oci.image.index.v1+json"
        ]
      },
      "contentHeaders": {
        "Content-Type": [ "application/json" ]
      },
      "contentString": "unauthorized"
    }
  ]
}

=== justeattakeaway/httpclient-interception/tests/HttpClientInterception.Tests/Bundles/content-as-json-array.json
{
  "$schema": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "id": "content-as-json-array-bundle",
  "comment": "An HTTP request bundle with content as a JSON array.",
  "version": 1,
  "items": [
    {
      "comment": "An HTTP request that returns a JSON array.",
      "uri": "https://api.github.com/orgs/justeattakeaway/repos",
      "contentFormat": "json",
      "contentJson": [
        "httpclient-interception"
      ]
    }
  ]
}

=== justeattakeaway/httpclient-interception/tests/HttpClientInterception.Tests/Bundles/http-request-bundle.json
{
  "$schema": "https://raw.githubusercontent.com/justeattakeaway/httpclient-interception/main/src/HttpClientInterception/Bundles/http-request-bundle-schema.json",
  "id": "test-http-request-bundle",
  "comment": "An HTTP request bundle for testing purposes.",
  "version": 1,
  "items": [
    {
      "id": "html",
      "comment": "A simple HTTP request that returns HTML.",
      "uri": "https://www.just-eat.co.uk/",
      "contentHeaders": {
        "content-type": [
          "text/html; charset=utf-8"
        ]
      },
      "contentString": "<html><head><title>Just Eat</title></head></html>"
    },
    {
      "id": "Base64",
      "comment": "A simple HTTP request where the content is encoded as a Base64 string.",
      "method": "GET",
      "uri": "https://www.just-eat.co.uk/order-history",
      "requestHeaders": {},
      "responseHeaders": {},
      "contentHeaders": {},
      "contentFormat": "base64",
      "contentString": "PGh0bWw+PGhlYWQ+PHRpdGxlPkp1c3QgRWF0PC90aXRsZT48L2hlYWQ+PC9odG1sPg==",
      "templateValues": {}
    },
    {
      "id": "JSON",
      "comment": "An HTTP request that returns JSON.",
      "priority": 1,
      "version": "1.1",
      "uri": "https://api.github.com/orgs/justeattakeaway",
      "requestHeaders": {
        "Accept": [
          "application/vnd.github.v3+json"
        ],
        "Authorization": [
          "token my-token"
        ],
        "User-Agent": [
          "My-App/1.0.0"
        ]
      },
      "responseHeaders": {
        "Access-Control-Allow-Origin": [
          "*"
        ],
        "Server": [
          "GitHub.com"
        ],
        "X-RateLimit-Limit": [
          "60"
        ]
      },
      "contentFormat": "json",
      "contentJson": {
        "id": 1516790,
        "login": "justeattakeaway",
        "url": "https://api.github.com/orgs/justeattakeaway"
      }
    }
  ]
}
